export const pricingData = [
  {
    "Part": "EMT Conduit 3/4\"",
    "IES": 0.83,
    "Wesco": 0.7434,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Conduit 1\"",
    "IES": 1.4422,
    "Wesco": 1.317,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": 1.32
  },
  {
    "Part": "EMT Conduit 1-1/4\"",
    "IES": 2.3382,
    "Wesco": 2.1362,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Conduit 1-1/2\"",
    "IES": 2.8548,
    "Wesco": 2.6093,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Conduit 2\"",
    "IES": 3.57645,
    "Wesco": 3.0255,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": 3.09
  },
  {
    "Part": "EMT Conduit 2-1/2\"",
    "IES": 4.9652,
    "Wesco": 4.6547,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Conduit 3\"",
    "IES": 6.288,
    "Wesco": 5.901,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Conduit 3/4\"",
    "IES": 2.58893,
    "Wesco": 1.81,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Conduit 1\"",
    "IES": 2.9672,
    "Wesco": 3.687,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Conduit 1-1/4\"",
    "IES": 4.2949,
    "Wesco": 3.8743,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Conduit 1-1/2\"",
    "IES": 3.7676,
    "Wesco": 5.2409,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Conduit 2\"",
    "IES": 5.66969,
    "Wesco": 5.2439,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Conduit 2-1/2\"",
    "IES": 9.739,
    "Wesco": 9.6573,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Conduit 3\"",
    "IES": 11.2187,
    "Wesco": 11.4111,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Conduit 1\"",
    "IES": NaN,
    "Wesco": 3.8841,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Conduit 1-1/4\"",
    "IES": NaN,
    "Wesco": 5.7087,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Conduit 1-1/2\"",
    "IES": NaN,
    "Wesco": 6.2865,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Conduit 2-1/2\"",
    "IES": NaN,
    "Wesco": 14.8476,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Straight Connector 3/4\"",
    "IES": 1.01369,
    "Wesco": 1.24,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Straight Connector 1\"",
    "IES": 2.6055,
    "Wesco": 1.63,
    "CED": 2.1,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Straight Connector 1-1/4\"",
    "IES": 4.7125,
    "Wesco": 4.07,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Straight Connector 1-1/2\"",
    "IES": 9.0415,
    "Wesco": 4.71,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Straight Connector 2\"",
    "IES": 6.75882,
    "Wesco": 5.91,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Straight Connector 2-1/2\"",
    "IES": 30.2615,
    "Wesco": 20.35,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Straight Connector 3\"",
    "IES": 38.1891,
    "Wesco": 26.1,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Straight Connector 3/4\"",
    "IES": 2.67839,
    "Wesco": 4.15,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Straight Connector 1\"",
    "IES": 4.3536,
    "Wesco": 4.9149,
    "CED": 7.99,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Straight Connector 1-1/4\"",
    "IES": 9.1996,
    "Wesco": 12.11,
    "CED": 11.35,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Straight Connector 1-1/2\"",
    "IES": 11.8279,
    "Wesco": 13.5921,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Straight Connector 2\"",
    "IES": 26.00055,
    "Wesco": 26.54,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Straight Connector 2-1/2\"",
    "IES": 101.3343,
    "Wesco": 97.41,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T Straight Connector 3\"",
    "IES": 139.1708,
    "Wesco": 96.83,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Threadless Connector 1\"",
    "IES": NaN,
    "Wesco": 7.3453,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Threadless Connector 1-1/4\"",
    "IES": NaN,
    "Wesco": 10.21,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Threadless Connector 1-1/2\"",
    "IES": NaN,
    "Wesco": 14.0332,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT R/T Coupling 3/4\"",
    "IES": 0.99088,
    "Wesco": 1.18,
    "CED": 1.5483,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT R/T Coupling 1\"",
    "IES": 1.33978,
    "Wesco": 2.31,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT R/T Coupling 1-1/4\"",
    "IES": 2.63927,
    "Wesco": 3.77,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT R/T Coupling 1-1/2\"",
    "IES": 3.84448,
    "Wesco": 4.92,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Coupling 3/4\"",
    "IES": 2.45627,
    "Wesco": 1.29,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Coupling 1\"",
    "IES": 4.5255,
    "Wesco": 2.9,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Coupling 1-1/4\"",
    "IES": 5.1986,
    "Wesco": 1.83,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Coupling 1-1/2\"",
    "IES": 6.762,
    "Wesco": 3.69,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Coupling 2\"",
    "IES": 7.88959,
    "Wesco": 2.83,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Coupling 2-1/2\"",
    "IES": 20.3952,
    "Wesco": 7.18,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "GRC Coupling 3\"",
    "IES": 25.3983,
    "Wesco": 8.88,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T 45 Connector 1\"",
    "IES": 8.19451,
    "Wesco": 9.029,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T 45 Connector 1-1/4\"",
    "IES": 17.3711,
    "Wesco": 14.9273,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T 90 Connector 3/4\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T 90 Connector 1\"",
    "IES": 7.605,
    "Wesco": 10.3793,
    "CED": 19.95,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T 90 Connector 1-1/4\"",
    "IES": 15.3468,
    "Wesco": 38.0184,
    "CED": 24.09,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T 90 Connector 1-1/2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "L/T 90 Connector 2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Transition Coupling 3/4\"",
    "IES": 8.88865,
    "Wesco": 7.0939,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Transition Coupling 1\"",
    "IES": 14.0398,
    "Wesco": 13.1412,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Transition Coupling 1-1/4\"",
    "IES": 28.069,
    "Wesco": NaN,
    "CED": 25.3333,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Transition Coupling 1-1/2\"",
    "IES": 40.2075,
    "Wesco": NaN,
    "CED": 36.04,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Transition Coupling  2\"",
    "IES": 56.03142,
    "Wesco": NaN,
    "CED": 47.08,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Transition Coupling 2-1/2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Myers Hub 3/4\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Myers Hub 1\"",
    "IES": 4.9243,
    "Wesco": 5.89,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Myers Hub 1-1/4\"",
    "IES": 6.26452,
    "Wesco": 8.44,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Myers Hub 1-1/2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Myers Hub 2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Short Threaded Nipple 1\"",
    "IES": 2.8621,
    "Wesco": 1.75,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Short Threaded Nipple 1-1/4\"",
    "IES": 3.7248,
    "Wesco": 2.14,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Lock Washer w/ Gasket 1-1/4\"",
    "IES": NaN,
    "Wesco": 2.954,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "KO Bushing 1-1/2\"",
    "IES": NaN,
    "Wesco": 0.6044,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "KO Seal 1-1/4\"",
    "IES": NaN,
    "Wesco": 20.77,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "KO Seal 2\"",
    "IES": NaN,
    "Wesco": 27.55,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Deep Strut",
    "IES": 2.33,
    "Wesco": 2.2823,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 2.06,
    "Elliot": NaN
  },
  {
    "Part": "Shallow Strut ",
    "IES": 1.7375,
    "Wesco": 1.6185,
    "CED": NaN,
    "CState": 1.64,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 1.44,
    "Elliot": NaN
  },
  {
    "Part": "Strut Strap 3/4\"",
    "IES": NaN,
    "Wesco": 1.3733,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Strut Strap 1\"",
    "IES": NaN,
    "Wesco": 1.564,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.62,
    "Elliot": NaN
  },
  {
    "Part": "Strut Strap 1-1/4\"",
    "IES": NaN,
    "Wesco": 1.9798,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.45,
    "Elliot": NaN
  },
  {
    "Part": "Strut Strap 1-1/2\"",
    "IES": NaN,
    "Wesco": 2.5109,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Strut Strap 3\"",
    "IES": 1.86412,
    "Wesco": 2.9308,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Unistrut Base 6 x 6 x 3-1/2",
    "IES": 20.59683,
    "Wesco": 46.8448,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Unistrut Splice Plate",
    "IES": 3.8093,
    "Wesco": 5.5055,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Hanger 3/4\"",
    "IES": 0.24346,
    "Wesco": 0.733,
    "CED": 0.575,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Hanger 1\"",
    "IES": 0.6213,
    "Wesco": 0.8404,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Hanger 1-1/4\"",
    "IES": 1.0002,
    "Wesco": 0.9973,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Hanger 1-1/2\"",
    "IES": 0.9214,
    "Wesco": 0.8194,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Hanger 2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Hanger 2-1/2\"",
    "IES": 0.7544,
    "Wesco": 2.2724,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "EMT Hanger 3\"",
    "IES": 0.9065,
    "Wesco": 2.9866,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Beam Clamp 1/4\"",
    "IES": 1.0003,
    "Wesco": 1.0906,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 1.12,
    "Elliot": NaN
  },
  {
    "Part": "Beam Clamp 3/8\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.51,
    "Elliot": NaN
  },
  {
    "Part": "All Thread 3/8\"",
    "IES": 0.749,
    "Wesco": 0.755,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Plastic Snap Bushing 1-1/2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Reducing Washer 2\" to 1-1/2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Reducing Washer 2\" to 1-1/4\"",
    "IES": 1.1742,
    "Wesco": 0.3912,
    "CED": NaN,
    "CState": 0.57,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Reducing Washer 2\" to 1\"",
    "IES": 1.2338,
    "Wesco": 0.5465,
    "CED": NaN,
    "CState": 1.08,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Reducing Washer 2\" to 3/4\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Reducing Washer 1-1/4\" to 1\"",
    "IES": 0.36165,
    "Wesco": 0.3611,
    "CED": NaN,
    "CState": 0.95,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Hex Bolt 1/4-20 X 1\" Zinc",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0549,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Hex Bolt 1/4-20 X 1\" SS",
    "IES": 0.3057,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.1924,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.2437,
    "Elliot": NaN
  },
  {
    "Part": "Hex Bolt 1/4-20 X 1/2\"",
    "IES": NaN,
    "Wesco": 0.0656,
    "CED": NaN,
    "CState": 0.0428,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Hex Bolt 3/8-16 X 1\"",
    "IES": 0.19769,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Hex Bolt 3/8-16 X 1-1/2\"",
    "IES": 0.2946,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.1697,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.16745,
    "Elliot": NaN
  },
  {
    "Part": "Hex Bolt 10-24x1\" SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.1905,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.15,
    "Elliot": NaN
  },
  {
    "Part": "Hex Bolt 10-24 X 1-1/2 \"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.13,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Pan Head Machine screw 10-24",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.1319,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Flat Washer 1/4\" Zinc",
    "IES": 0.0546,
    "Wesco": 0.0418,
    "CED": NaN,
    "CState": 0.0252,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.03,
    "Elliot": NaN
  },
  {
    "Part": "Flat Washer 1/4\" SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0225,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.06468,
    "Elliot": NaN
  },
  {
    "Part": "Flat Washer 3/8\"",
    "IES": 0.08389,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0432,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Flat Washer #10 SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.04,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Spring Nut 1/4\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.35,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Spring Nut 3/8\"",
    "IES": 0.9759,
    "Wesco": 1.4184,
    "CED": NaN,
    "CState": 0.364,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.42,
    "Elliot": NaN
  },
  {
    "Part": "Lay-in-Lug",
    "IES": 1.56,
    "Wesco": 1.1,
    "CED": NaN,
    "CState": 4.32,
    "1Monroe": 3.5,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Hex Nut 3/8-16",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0423,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.06844,
    "Elliot": NaN
  },
  {
    "Part": "Hex Nut 3/8-16 SS",
    "IES": 0.2247,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Hex Nut 10-24 SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0441,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.0225,
    "Elliot": NaN
  },
  {
    "Part": "Hex Nut 1/4\"-20 SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0384,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Copper C-Tap 4 AWG",
    "IES": 5.67,
    "Wesco": 1.78,
    "CED": NaN,
    "CState": 5.94,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Fender Washer 3/8\" X 1-1/4\"",
    "IES": 0.1115,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0774,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.07868,
    "Elliot": NaN
  },
  {
    "Part": "Fender Washer 1/4\" X 1\" SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.06,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Lock Washer 1/4\" SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0255,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.03,
    "Elliot": NaN
  },
  {
    "Part": "Lock Washer 3/8\"",
    "IES": 0.04819,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.03,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Lock Washer #10 SS",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.06,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "SGB4",
    "IES": 9.563,
    "Wesco": 8.41,
    "CED": NaN,
    "CState": 4.35,
    "1Monroe": 2.8,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Weeb 1/4\" UIR",
    "IES": 1.65,
    "Wesco": 1.6144,
    "CED": 1.76,
    "CState": NaN,
    "1Monroe": 1.39,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "5/16 x 1\" self tapper screw",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.4472,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "1/2\" x 5-1/2\" concrete wedge anchors",
    "IES": 2.01678,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Ground Bar (4 Port #4 Wire)",
    "IES": NaN,
    "Wesco": 23.45,
    "CED": NaN,
    "CState": 13.5,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Ground Bar (6-Port #14 to 2/0)",
    "IES": NaN,
    "Wesco": 28.15,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Ground Bar (8-Port 4/0 Wire)",
    "IES": 98.6,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Bond Bushing 1\"",
    "IES": 3.42704,
    "Wesco": 4.648,
    "CED": 3.7,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Bond Bushing 1-1/4\"",
    "IES": 4.59493,
    "Wesco": 7.3694,
    "CED": 4.7,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Bond Bushing 1-1/2\"",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Bond Bushing 2-1/2\"",
    "IES": 13.31775,
    "Wesco": 23.0464,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Reducing Bushing 1-1/2\" to 1-1/4\"",
    "IES": 5.27942,
    "Wesco": 4.9594,
    "CED": 0.375,
    "CState": 4.696,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Reducing Bushing 3\" to 2-1/2\"",
    "IES": NaN,
    "Wesco": 42.2357,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Heyco Management Clip",
    "IES": 0.27,
    "Wesco": 0.2832,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": 0.17,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Tyco Connector Male",
    "IES": 1.35,
    "Wesco": 1.62,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": 1.5,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Tyco Connector Female",
    "IES": 1.35,
    "Wesco": 1.62,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": 1.5,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Staubli MC4 Male",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": 1.29,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Staubli MC4 Female",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": 1.29,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Staubli MC4 Splitter 2M1F",
    "IES": 5.8,
    "Wesco": 9.08,
    "CED": 5.87,
    "CState": NaN,
    "1Monroe": 6.35,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Staubli MC4 Splitter 2F1M",
    "IES": 6.45,
    "Wesco": 9.08,
    "CED": 5.67,
    "CState": NaN,
    "1Monroe": 6.35,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Staubli In-Line Fuse",
    "IES": 26.19,
    "Wesco": 37.15,
    "CED": 27.69,
    "CState": NaN,
    "1Monroe": 21,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Amphenol Male - H4SMC6DM",
    "IES": NaN,
    "Wesco": NaN,
    "CED": 2.35,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Amphenol Female - H4SFC6DM",
    "IES": NaN,
    "Wesco": NaN,
    "CED": 2.35,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Cat5e Direct Burial Shld 1000' (Blk)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": 209.99,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Cat5e Plenum Shld 1000' (Wht)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": 0.3,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Cat5e Field Term Plug Shld (12x)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": 68.99,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Cat5e Tooless Keystone Jack Shld (12x)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": 31.16,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Cat5e RJ45 Pass-Through Conns (100x)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": 41.79,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Cat5e Large Cut to Fit Boots (100x)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": 12.99,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Cat5e Small Cut to Fit Boots (100x)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": 12.99,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Blue wire nuts",
    "IES": NaN,
    "Wesco": 0.32642,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "J-Box 2 Gang 5 1\" hole",
    "IES": NaN,
    "Wesco": 16.5385,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "J- Box 6x6x4 A6R64",
    "IES": NaN,
    "Wesco": 27.48,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Lighting - Single Gang WP J-Box",
    "IES": 3.24429,
    "Wesco": 12.3531,
    "CED": 12.2356,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Lighting - Key Switch 20A",
    "IES": 37.342,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Lighting - WP Switch Covers",
    "IES": 7.04556,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Polaris Tap 1/0-14 AWG",
    "IES": NaN,
    "Wesco": 24.41,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - #4 bare copper wire",
    "IES": 0.85099,
    "Wesco": 0.91612,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #12 (Red)",
    "IES": 0.15414,
    "Wesco": 0.16109,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #12 (White)",
    "IES": 0.15414,
    "Wesco": 0.16109,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #12 (Green)",
    "IES": NaN,
    "Wesco": 0.16109,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - PV Wire #10 2KV (red)",
    "IES": 0.34,
    "Wesco": 0.30104,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - PV Wire #10 2KV (black)",
    "IES": 0.34,
    "Wesco": 0.30104,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #10 (Green)",
    "IES": NaN,
    "Wesco": 0.25203,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #8 (Brown)",
    "IES": NaN,
    "Wesco": 0.48717,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #8 (Orange)",
    "IES": NaN,
    "Wesco": 0.48717,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #8 (Yellow)",
    "IES": NaN,
    "Wesco": 0.48717,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #8 (Green)",
    "IES": 0.4916,
    "Wesco": 0.48717,
    "CED": 0.53084,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #6 (Brown)",
    "IES": NaN,
    "Wesco": 0.74952,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #6 (Orange)",
    "IES": NaN,
    "Wesco": 0.74952,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #6 (Yellow)",
    "IES": NaN,
    "Wesco": 0.74952,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #6 (Green)",
    "IES": 0.75635,
    "Wesco": 0.74952,
    "CED": 0.81672,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #4 (Brown)",
    "IES": 1.12436,
    "Wesco": 1.14697,
    "CED": 1.23476,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #4 (Orange)",
    "IES": 1.12436,
    "Wesco": 1.14697,
    "CED": 1.23476,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #4 (Yellow)",
    "IES": 1.12436,
    "Wesco": 1.14697,
    "CED": 1.23476,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #3 (Brown)",
    "IES": 1.41816,
    "Wesco": 1.44669,
    "CED": 1.55767,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #3 (Orange)",
    "IES": 1.41816,
    "Wesco": 1.44669,
    "CED": 1.55767,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #3 (Yellow)",
    "IES": 1.41816,
    "Wesco": 1.44669,
    "CED": 1.55767,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #3 (Green)",
    "IES": 1.41816,
    "Wesco": 1.44669,
    "CED": 1.55767,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #2 (Brown)",
    "IES": NaN,
    "Wesco": 1.81082,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #2 (Orange)",
    "IES": NaN,
    "Wesco": 1.81082,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #2 (Yellow)",
    "IES": NaN,
    "Wesco": 1.81082,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #2 (Green)",
    "IES": NaN,
    "Wesco": 1.81082,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #1 (Brown)",
    "IES": NaN,
    "Wesco": 2.07545,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #1 (Orange)",
    "IES": NaN,
    "Wesco": 2.07545,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper #1 (Yellow)",
    "IES": NaN,
    "Wesco": 2.07545,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 1/0 (Brown)",
    "IES": NaN,
    "Wesco": 2.55541,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 1/0 (Orange)",
    "IES": NaN,
    "Wesco": 2.55541,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 1/0 (Yellow)",
    "IES": NaN,
    "Wesco": 2.55541,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 1/0 (Green)",
    "IES": NaN,
    "Wesco": 2.55541,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 4/0 (Brown)",
    "IES": NaN,
    "Wesco": 4.95885,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 4/0 (Orange)",
    "IES": NaN,
    "Wesco": 4.95885,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 4/0 (Yellow)",
    "IES": NaN,
    "Wesco": 4.95885,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 4/0 (Grey)",
    "IES": NaN,
    "Wesco": 4.95885,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 4/0 (Green)",
    "IES": NaN,
    "Wesco": 4.95885,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 250 KCMIL (Brown)",
    "IES": NaN,
    "Wesco": 5.84437,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 250 KCMIL (Orange)",
    "IES": NaN,
    "Wesco": 5.84437,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 250 KCMIL (Yellow)",
    "IES": NaN,
    "Wesco": 5.84437,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper 250 KCMIL (Grey)",
    "IES": NaN,
    "Wesco": 5.84437,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper KCMIL 400 (Brown)",
    "IES": 8.963149,
    "Wesco": 9.33553,
    "CED": 8.93952,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper KCMIL 400 (Orange)",
    "IES": 8.963149,
    "Wesco": 9.33553,
    "CED": 8.93952,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Copper KCMIL 400 (Yellow)",
    "IES": 8.963149,
    "Wesco": 9.33553,
    "CED": 8.93952,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #6 (Brown)",
    "IES": NaN,
    "Wesco": 0.25715,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #6 (Orange)",
    "IES": NaN,
    "Wesco": 0.25715,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #6 (Yellow)",
    "IES": NaN,
    "Wesco": 0.25715,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #6 (Green)",
    "IES": NaN,
    "Wesco": 0.25715,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #4 (Brown)",
    "IES": NaN,
    "Wesco": 0.31766,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #4 (Orange)",
    "IES": NaN,
    "Wesco": 0.31766,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #4 (Yellow)",
    "IES": NaN,
    "Wesco": 0.31766,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #4 (Green)",
    "IES": NaN,
    "Wesco": 0.31766,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #2 (Brown)",
    "IES": NaN,
    "Wesco": 0.40302,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #2 (Orange)",
    "IES": NaN,
    "Wesco": 0.40302,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #2 (Yellow)",
    "IES": NaN,
    "Wesco": 0.40302,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #2 (Green)",
    "IES": NaN,
    "Wesco": 0.40302,
    "CED": 0.40921,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #1 (Brown)",
    "IES": NaN,
    "Wesco": 0.55542,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #1 (Orange)",
    "IES": NaN,
    "Wesco": 0.55542,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #1 (Yellow)",
    "IES": NaN,
    "Wesco": 0.55542,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum #1 (Green)",
    "IES": NaN,
    "Wesco": 0.55542,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum 2/0 (Green)",
    "IES": NaN,
    "Wesco": 0.7416,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum 2/0 (Grey)",
    "IES": NaN,
    "Wesco": 0.7416,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum 3/0 (Grey)",
    "IES": NaN,
    "Wesco": 0.92073,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum 3/0 (Green)",
    "IES": NaN,
    "Wesco": 0.92073,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum 4/0 (Green)",
    "IES": NaN,
    "Wesco": 1.0234,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 250 (Brown)",
    "IES": 0.965592,
    "Wesco": 1.25672,
    "CED": 1.15333,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 250 (Orange)",
    "IES": 0.965592,
    "Wesco": 1.25672,
    "CED": 1.15333,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 250 (Yellow)",
    "IES": 0.965592,
    "Wesco": 1.25672,
    "CED": 1.15333,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 250 (Green)",
    "IES": NaN,
    "Wesco": 1.25672,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 250 (Grey)",
    "IES": NaN,
    "Wesco": 1.25672,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 350 (Brown)",
    "IES": 1.355914,
    "Wesco": 1.76514,
    "CED": 1.61993,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 350 (Orange)",
    "IES": 1.355914,
    "Wesco": 1.76514,
    "CED": 1.61993,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 350 (Yellow)",
    "IES": 1.355914,
    "Wesco": 1.76514,
    "CED": 1.61993,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 400 (Brown)",
    "IES": NaN,
    "Wesco": 2.06356,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 400 (Orange)",
    "IES": NaN,
    "Wesco": 2.06356,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 400 (Yellow)",
    "IES": NaN,
    "Wesco": 2.06356,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 500 (Brown)",
    "IES": NaN,
    "Wesco": 2.24901,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 500 (Orange)",
    "IES": NaN,
    "Wesco": 2.24901,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum KCMIL 500 (Yellow)",
    "IES": NaN,
    "Wesco": 2.24901,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum  KCMIL 500 (Grey)",
    "IES": 1.749463,
    "Wesco": 2.24901,
    "CED": 2.08864,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire - Aluminum  KCMIL 500 (Green)",
    "IES": 1.749463,
    "Wesco": 2.24901,
    "CED": 2.08864,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Heyco Sunbundler",
    "IES": NaN,
    "Wesco": 0.54,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": 0.47,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Mule Tape 3000'",
    "IES": NaN,
    "Wesco": 133.08,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Jet Line 6500'",
    "IES": 85.406,
    "Wesco": 42.55,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Wire Lube (5 gal)",
    "IES": 82.926,
    "Wesco": 84.44,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Drill Bit 13/64",
    "IES": NaN,
    "Wesco": 1.3,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Pipe Wrap 20 mil",
    "IES": 15.406,
    "Wesco": 14.78,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "PVC Male Adapter 1\"",
    "IES": 0.61614,
    "Wesco": 0.3917,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "PVC Male Adapter 1-1/2\"",
    "IES": 0.99997,
    "Wesco": 0.7179,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "PVC Male Adapter 2\"",
    "IES": 1.37908,
    "Wesco": 0.8811,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "PVC Male Adapter 2-1/2\"",
    "IES": NaN,
    "Wesco": 1.4127,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "PVC Female Adapter 1\"",
    "IES": NaN,
    "Wesco": 0.4924,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Close Nipple 1\"",
    "IES": 3.36,
    "Wesco": 1.68,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Sealing lock ring 1\"",
    "IES": 1.54,
    "Wesco": 2.42,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Flat Washer M8 (SS)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0372,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.03225,
    "Elliot": NaN
  },
  {
    "Part": "Lock Washer M8 (SS)",
    "IES": NaN,
    "Wesco": NaN,
    "CED": NaN,
    "CState": 0.0657,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": 0.0384,
    "Elliot": NaN
  },
  {
    "Part": "Data Manager",
    "IES": NaN,
    "Wesco": 956.03,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "SMA DC Term Cover (TripowerX)",
    "IES": NaN,
    "Wesco": 56.85,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Splice Box 6\" Round",
    "IES": 14.2,
    "Wesco": NaN,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Expansion Joint 1\"",
    "IES": NaN,
    "Wesco": 135,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Bond Jumper 1/2\" to 1\"",
    "IES": NaN,
    "Wesco": 55.94,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Expansion Joint  2-1/2\"",
    "IES": NaN,
    "Wesco": 333.75,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Bond Jumper 1/2\" to 4\"",
    "IES": NaN,
    "Wesco": 108.43,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Expansion Joint 2\" (Internal ground)",
    "IES": NaN,
    "Wesco": 336.38,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Conduit Body LB 2\"",
    "IES": NaN,
    "Wesco": 21.67,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Conduit Body LB 2-1/2\"",
    "IES": NaN,
    "Wesco": 160.78,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Prebent EMT 90 conduit 2-1/2\"",
    "IES": NaN,
    "Wesco": 22.24,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Prebent EMT 90 conduit 2\"",
    "IES": NaN,
    "Wesco": 9.06,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "INVERTERS - Tripower X 20kW",
    "IES": NaN,
    "Wesco": 2848.2,
    "CED": 3030,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "INVERTERS - Tripower X 25kW",
    "IES": NaN,
    "Wesco": 2975,
    "CED": 3184,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "INVERTERS - Tripower X 30kW",
    "IES": NaN,
    "Wesco": 3210,
    "CED": 3395,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "OSB Plywood 4'x'4'23/32\"",
    "IES": NaN,
    "Wesco": 21.81,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Post 4\"x4\"x8'",
    "IES": NaN,
    "Wesco": 12.72,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Styrofoam Sheet 4'x4'x1\"",
    "IES": NaN,
    "Wesco": 9.98,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Ram Board Tape 164'",
    "IES": NaN,
    "Wesco": 9.98,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Ram Board 100' Roll",
    "IES": NaN,
    "Wesco": 36.98,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Chalk Bottle",
    "IES": NaN,
    "Wesco": 3.47,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  },
  {
    "Part": "Chalk Reel",
    "IES": NaN,
    "Wesco": 12.97,
    "CED": NaN,
    "CState": NaN,
    "1Monroe": NaN,
    "Border St.": NaN,
    "trueCABLE": NaN,
    "Nefco": NaN,
    "Elliot": NaN
  }
];